sudo: false
language: rust
cache: cargo

rust:
  - nightly
  - beta
  - stable

before_script:
  - rustup component add clippy

script:
  - cargo build --verbose
  - cargo test --verbose
  - if [[ "$TRAVIS_RUST_VERSION" = "stable" ]]; then cargo clippy -- -D warnings; fi
