sudo: false
language: rust
cache: cargo

rust:
  - nightly
  - beta
  - stable

before_script:
  - rustup component add clippy || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo clippy -- -D warnings
