[package]
name = "optizee"
version = "0.1.0"
authors = ["Jonathan Stites <mail@jonstites.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
ndarray = "0.13.0"
rayon = "1.2.0"

[profile.test]
opt-level = 3



[profile.release]
debug = true
