[package]
name = "optizee"
version = "0.1.0"
authors = ["Jonathan Stites <mail@jonstites.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
ndarray-parallel = "0.9.1"
itertools = {version = "0.8.0"}
ndarray = { version = "0.13.0", features = ["blas"] }
blas-src = { version = "0.2.0", default-features = false, features = ["openblas"] }
openblas-src = { version = "0.6.0", default-features = false, features = ["cblas", "system"] }

[profile.test]
opt-level = 3

[features]
"generate_constants" = []

[[bin]]
name = "generate_constants"
path = "src/bin/generate_constants.rs"

[profile.release]
debug = true
